SET(CMAKE_SYSTEM_NAME Windows)
SET(CMAKE_C_COMPILER cl)
SET(CMAKE_CXX_COMPILER cl)

set(CMAKE_C_FLAGS_DEBUG "/Od /MT /Zi")
set(CMAKE_CXX_FLAGS_DEBUG "/Od /MT /Zi")

set(CMAKE_C_FLAGS_RELEASE "/Ox /Ob2 /Gw /Gy /GL")
SET(CMAKE_CXX_FLAGS_RELEASE "/Ox /Ob2 /Gw /Gy /GL")
